% showCalibrationPatternV2
% Opens the V2 calibration pattern as a full-screen visual aid.

clear hFig
hFig = generateCalibrationPatternV2( ...
    'FullScreen', true, ...
    'MonitorIndex', 1, ...
    'RingStep', 0.08, ...
    'AngleStep', 10, ...
    'CenterHoleRadius', 0.085);
