function fieldNames = getCalibrationFieldNames()
%GETCALIBRATIONFIELDNAMES GUI fields stored in coords.mat.
fieldNames = {'screenRadius','screenX','screenY','screenZ', ...
    'mirrorRadius','mirrorX','mirrorY','mirrorZ', ...
    'projectorX','projectorY','projectorZ', ...
    'x0','y0','x1','y1','x2','y2'};
end